# Generated by Django 5.2.8 on 2025-11-17 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userplatform'),
        ),
    ]
